

services:
  db:
    image: postgres:15
    container_name: pg-clinica
    restart: always
    environment:
      POSTGRES_DB: clinica_vet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/15/data  # <- Corregido aquÃ­

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-clinica
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinica.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
