

services:
  db:
    image: postgres:15
    container_name: pg-clinica
    restart: always
    environment:
      POSTGRES_DB: clinica_vet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-clinica
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinica.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # backend:
#   build: ./backend
#   container_name: backend-clinica
#   restart: always
#   environment:
#     NODE_ENV: development
#   ports:
#     - "3000:3000"
#   depends_on:
#     - db

# frontend:
#   build: ./frontend
#   container_name: frontend-clinica
#   restart: always
#   environment:
#     NODE_ENV: development
#   ports:
#     - "4200:80"
#   depends_on:
#     - backend


volumes:
  db-data:
  pgadmin-data:

# lo comentado es porque solo queremos levantar pg-clinica y pgadmin 